name: Report a Bug🐛
description: Report a bug so that we can Improve :)
title: '[Bug]: '
labels:
  - Bug
body:
  - type: textarea
    id: what_is_the_bug
    attributes:
      label: What is the bug?
      description: >-
        Please provide steps on how we can reproduce the bug, you may also
        provide screenshots
    validations:
      required: true
  - type: textarea
    id: info
    attributes:
      label: Info String
      description: >-
        We need some information before, Please copy & paste your info string from Disland. (Your info string does not contain sensitive information)
      placeholder: User Id, import.meta, etc, etc
    validations:
      required: true
  - type: checkboxes
    id: maybe_duplicate
    attributes:
      label: Before you submit!
      description: We wanna know somethings.
      options:
        - label: Have you checked for other duplicate issues?
          required: true
        - label: Have you read the rules?
          required: true
