blank_issues_enabled: false
contact_links:
  - name: Community Support
    url: https://github.com/orgs/dislnd/discussions
    about: Please ask and answer questions here.
  - name: Vulnerability Reporting
    url: https://twitter.com/dislandapp
    about: Please report security vulnerabilities in our dms (This will probably not be the primary way to report them in the future)
