blank_issues_enabled: false
contact_links:
  - name: Community Support
    url: https://github.com/orgs/dislnd/discussions
    about: Please ask and answer questions here.
  - name: Vulnerability Reporting
    url: https://github.com/dislnd/Issue-Tracker/blob/master/VULNERABILITY.md
    about: Read VULNERABILITY.md
