blank_issues_enabled: false
contact_links:
  - name: Community Support
    url: https://github.com/orgs/dislnd/discussions
    about: Please ask and answer questions here.
  - name: Vulnerability Reporting
    url: mailto:dislandapp@googlegroups.com
    about: Please email security vulnerabilities to dislandapp@googlegroups.com
